#version: "3.8"

services:
  kuva-bo:
    image: kuva-bo
    container_name: kuva-bo
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.development
    ports:
      - 3000:3000
