export const RESET_ERROR = 'RESET_ERROR'

// auth
export const TOKENS_FETCHING = 'TOKENS_FETCHING'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const AUTHENTICATOR_FETCHING = 'AUTHENTICATOR_FETCHING'
export const AUTHENTICATOR_CONFIRM = 'AUTHENTICATOR_CONFIRM'
export const AUTHENTICATOR_DISABLE = 'AUTHENTICATOR_DISABLE'

// user
export const USER_FETCHING = 'USER_FETCHING'

// display
export const SET_DISPLAY_DATA = 'SET_DISPLAY_DATA'

// permissions
export const PERMISSION_LIST_FETCHING = 'PERMISSION_LIST_FETCHING'
export const USER_PERMISSION_LIST_FETCHING = 'USER_PERMISSION_LIST_FETCHING'

// loader
export const SET_START_LOADER = 'SET_START_LOADER'
export const SET_STOP_LOADER = 'SET_STOP_LOADER'
