// auth
export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_FINISHED = 'FETCH_USER_FINISHED'
export const USER_FETCHING = 'USER_FETCHING'

// display
export const SET_DISPLAY_DATA = 'SET_DISPLAY_DATA'
